### ISSUE TITLE
Affichage du champ dans lors de la création/édition d'un ticket

### ISSUE THREAD

**Issue by ducemmanuel** [nenes25/mantisbt_uploadfiles#1]
Hello,

It works when I edit an issue, but when I create a new issue I didn't see the function to drag & drop attachments.

v 1.2.16 of mantis (tested with chrome & IE)

Emmanuel

**Comment by nenes25** [comment]
Hello,

Thanks for your return, but this is not a bug.

The drag & drop uploader can't work during the creation of a new issue because all the required parameters are not present in this step.

For now it's not planed to work on this behaviour.

Regards,
Hervé
